; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


; При изменении разметки flash памяти, обязательно внести исправления
; в скрипт post_build.py

[env:esp12e]
platform = espressif8266
board = nodemcu
framework = arduino
upload_port = COM13
upload_speed = 921600
monitor_speed = 115200
board_build.ldscript = eagle.flash.4m2m.ld
lib_deps = 
	bblanchon/ArduinoJson@=7.4.2
	crankyoldgit/IRremoteESP8266@=2.8.6
	links2004/WebSockets@=2.7.1
board_build.filesystem = littlefs
extra_scripts = post_build.py

[env:esp32]
platform = espressif32
framework = arduino
board = nodemcu-32s
upload_port = COM13
upload_speed = 921600
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = partitions.csv
lib_deps = 
	bblanchon/ArduinoJson@=7.4.2
	crankyoldgit/IRremoteESP8266@=2.8.6
	links2004/WebSockets@=2.7.1
	
extra_scripts = post_build.py

[env:esp32-c3]
platform = espressif32
framework = arduino
board = esp32-c3-devkitm-1
upload_port = COM13
upload_speed = 921600
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = partitions.csv
lib_deps = 
	bblanchon/ArduinoJson@=7.4.2
	crankyoldgit/IRremoteESP8266@=2.8.6
	links2004/WebSockets@=2.7.1
extra_scripts = post_build.py